export const BOOKS = {
    GET_ALLBOOKS: 'GET_ALLBOOKS',
    GET_ALLBOOKS_SUCCESS: 'GET_ALLBOOKS_SUCCESS',
    GET_ALLBOOKS_FAILED: 'GET_ALLBOOKS_FAILED',
    ALLBOOKS_FETCH_START: 'ALLBOOKS_FETCH_START',
    ALLBOOKS_FETCH_FINISHED: 'ALLBOOKS_FETCH_FINISHED',

    GET_BOOK: 'GET_BOOK',
    GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
    GET_BOOK_FAILED: 'GET_BOOK_FAILED',
    BOOK_FETCH_START: 'BOOK_FETCH_START',
    BOOK_FETCH_FINISHED: 'BOOK_FETCH_FINISHED',
}

export const FILTER = {
    CHANGE_FILTER: 'CHANGE_FILTER',
    CHANGE_FILTER_SET: 'CHANGE_FILTER_SET',
}